### ISSUE TITLE
devenv shell fails with AttributeError

### ISSUE THREAD

**Issue by logileifs** [gzur/devenv#4] opened 2019-06-20 11:34 UTC
`$ devenv shell`
```
Traceback (most recent call last):
  File "/home/logi/.virtualenvs/floti/bin/devenv", line 11, in <module>
    load_entry_point('devenv==0.2.0', 'console_scripts', 'devenv')()
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/devenv-0.2.0-py3.6.egg/devenv/cli.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/devenv-0.2.0-py3.6.egg/devenv/lib.py", line 3, in <module>
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/docker-4.0.2-py3.6.egg/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/docker-4.0.2-py3.6.egg/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/docker-4.0.2-py3.6.egg/docker/api/client.py", line 8, in <module>
    import websocket
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/websocket_client-0.56.0-py3.6.egg/websocket/__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/websocket_client-0.56.0-py3.6.egg/websocket/_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/websocket_client-0.56.0-py3.6.egg/websocket/_core.py", line 34, in <module>
    from ._handshake import *
  File "/home/logi/.virtualenvs/floti/lib/python3.6/site-packages/websocket_client-0.56.0-py3.6.egg/websocket/_handshake.py", line 40, in <module>
    if six.PY34:
AttributeError: module 'six' has no attribute 'PY34'
```

**Comment by gzur** [comment] 2019-06-22 00:37
Thanks for reporting this. I'm away on vacation, but I'll take a look when I get back.

**Comment by gzur** [comment] 2019-06-24 22:38
I was unable to reproduce this locally myself, but it appears to have been an intermittent issue with the `six` library, which is a dependency of the docker pip package, which is probably related to old versions of `six` that shipped with old debian downstreams (pre 2015).

What platform are you running on?
Does fixing the version of six (by way of the new requirements.txt) help?

**Comment by gzur** [comment] 2020-02-20 21:29
I am unable to repro this and there has been no follow-up. 

Closing this. Feel free to re-open if you still encounter this issue.

**Closed as completed by gzur** 2020-02-20 21:29 UTC
